# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: macOS-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    architecture: 'x64'

- script: |
    sudo apt-get install build-essential libgtk-3-dev libgstreamer-plugins-base1.0-dev
  displayName: 'Add GTK 3 for Linux'
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- script: python -m pip install --upgrade pip
  displayName: 'Upgrade Pip'

- script: python -m pip install .
  displayName: 'Install Deps'

- script: |
    pyinstaller -y macos.spec
  displayName: 'Build pyInstaller Application'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
    archiveFile: '$(Build.SourcesDirectory)/dist.zip'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: '$(Agent.OS)'
    pathtoPublish: '$(Build.SourcesDirectory)/dist.zip'