[tool.poetry]
name = "camtrapdb_workbench"
version = "0.0.0"
description = ""
authors = ["Ben Evans <ben@bluechimp.io>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
