name: Build for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "poetry"
      - run: poetry install
      - name: Build Windows App
        run: poetry run pyinstaller win.spec
      - uses: actions/upload-artifact@v3
        with:
          name: Windows App
          path: "dist/MegaDetector Desktop.exe"