name: Build for MacOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configuring conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: md-desktop
          environment-file: environment.yml
      - name: Build MacOS App
        shell: bash -l {0}
        run: pyinstaller macos.spec
      - name: Zip MacOS App
        run: zip -r macos.zip "dist/MegaDetector Desktop.app"
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS App
          path: macos.zip
